### PR TITLE
Add Comment, Uncomment, Remove and Update functions

### PR DESCRIPTION
**Pull request by seanjseymour**
Helper functions to be used in conjunction with the existing Get-IniContent and Out-IniFile functions in order to comment, uncomment, remove or update ini entries. See detailed examples in each function's documentation.

### CODE REVIEW

**Comment by lipkau** [comment]
Hello Sean.

I like the idea of creating additional function to handle simple task with ini files.
_Functions like `Update-IniContent` would not need an extra function, as the user could manipular the output object_

However I would require you to change some things in your PR:
* [ ] Only use approved verbs: Comment-IniContent --> **Add-IniComment**, Uncomment-IniContent --> **Remove-IniComment**
* [ ] Rename Update-IniContent to **Set-IniContent** _(As **Set** is most commonly used for a function that can Add and Change)_
* [ ] extract `Convert-IniEntryToComment` to it's own file/function but not included in the exported functions (so it is an module internal function). This also allows for better testing.
* [ ] Make the `Write-Debug` in the existing functions consisted with the ones you made
* [ ] Add a space in `Write-Debug(` --> `Write-Debug (`. As this reads (at least to me) better as a positional parameter
* [ ] same as above for `Write-Verbose(`
* [ ] Why this part: `if ($PSBoundParameters['Debug']) { $DebugPreference = 'Continue' }
        Write-Debug "DebugPreference: $DebugPreference"`? In a function with `[CmdletBinding()]` the presence of the parameter **-Debug** changes the value of `$DebugPreference` already.
* [ ] Make `[String]$CommentChar` a char array --> `[char[]]$CommentChar`, as each CommentChar should be of type **char**

I appreciate your effort. :smile:

**Comment by seanjseymour** [comment]
Thanks Oliver. I added these additional functions to support some internal analysts who are technical enough to run PowerShell commands, but they are not necessarily able to do stuff like safely manipulate the ini object that Get-IniContent provides.  

I appreciate you taking the time to make these suggestions, and I should have time to update the code this week.

As far as your question regarding $DebugPreference, I added that because I was running into the situation described [here](https://learn-powershell.net/2014/06/01/prevent-write-debug-from-bugging-you/).

**Comment by seanjseymour** [comment]
Do you have a suggestion on the alias names? Based on your initial alias names for Get-IniContent (get-ini) and Out-IniFile (set-ini) , I'm struggling to come up with something short for Add-IniComment and Remove-IniComment that also doesn't confuse users with Remove-IniContent and Update-IniContent. 

I read the alias guidelines [here ](https://msdn.microsoft.com/en-us/library/dd878329%28v=vs.85%29.aspx) and based on that I was thinking we could switch to multi-letter aliases like so:

- gic for Get-IniContent
- oif for Out-IniFile

But then Remove-IniComment and Remove-IniContent would both result in an alias of 'ric'. 

Or should I just not provide aliases for these additional functions?

**Comment by lipkau** [comment]
* **debug**  
I like this debug output without the inquery. please add that to other functions if relevant
* **naming and alias**  
3 letter alias is fine. maybe rename Remove-IniContent to Remove-IniEntry? would change the alias

**Comment by seanjseymour** [comment]
Great. I will also plan on updating Get-IniContent and Out-IniFile to the 3 letter convention unless I hear otherwise from you.

**Comment by seanjseymour** [comment]
OK, I have these changes ready to go but wanted to run something by you. 

In Convert-IniCommentToEntry, I agree that $CommentChar needs to be a char array since the user may not know what commenting style is used in the target ini. I've made that change and made sure it uncomments entries commented out with any of the characters provided.

However, for Convert-IniEntryToComment, the user is deciding to comment out an existing entry. So we need to comment out the existing entry with the comment character that they give us, or use the default semicolon character. But supporting a character array for this function doesn't make sense, because in the end we have to use **one** character to use as a comment. So for this function, I was thinking to keep $CommentChar as a string instead of a char array. Thoughts?

**Comment by lipkau** [comment]
Yes.
String Would allow "hello world" to be a comment char.
My suggestion:
* [char] --> but would give a type mismatch if a function passes its value
and is array
* [char[]] --> and when using it, call $commentChar[0]

**Comment by seanjseymour** [comment]
Good point on preventing random strings for comments. I'm leaning towards keeping the char array for compatibility as you mentioned. I had been testing the change with $commentChar[0] anyway and that's working fine. I'll just add a usage note about it in the help documentation.

**Comment by seanjseymour** [comment]
I updated the pull request with all the changes. Please review when you have some time. Thanks!

**Comment by lipkau** [comment]
Hi Sean

Did you run pester?
There is an error in your tests:
* [ ] the file for the tests of `Set-IniContent` is named `Set-IniComment.Tests.ps1`

please fix this


otherwise, your PR looks good

**Comment by seanjseymour** [comment]
My apologies Oliver, I ran pester on PsIni.Tests but I think I forgot to run the separate tests for the aliases. I've fixed the file name. And yes, please feel free to fix anything you see that bugs you.

**Comment by lipkau** [comment]
Merged. I will be fixing some minor stuff soon

**Comment by lipkau** [comment]
I regret not having finished the wiki documentation. If I had, I would force you to add your stuff to the documentation :smile:

**Comment by seanjseymour** [comment]
I can do that. Didn't notice the wiki before but I can certainly help out. Looks like you made a great start on it.

**Comment by lipkau** [comment]
another thing:
in **Set-IniContent.ps1**, why not use `[String]$Sections` as `[string[]]`?
this way, it would not be necessary to `[string]$SectionDelimiter = ',',`

**Comment by seanjseymour** [comment]
Hi Oliver, I will try and take a look this weekend. Thanks for your patience.

**Pull request merged**
